package smokeTest;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

//import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class VerifyNOPLoginTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		
		
		//app1
//		System.setProperty("webdriver.chrome.driver", "C:/Users/91995/Downloads/chromedriver_win32 (3)/chromedriver.exe");
//		driver = new ChromeDriver();
		
		
		
		//app2 ----- 4.3.3
//		WebDriverManager.chromedriver().setup();
//		driver = new ChromeDriver();
		
		
		//app2 ----- 5.0.0
//		driver = WebDriverManager.chromedriver().create();
//				driver = new ChromeDriver();
		
		
		//app3 ----- 4.6+ SeleniumManager ------ 
		
		driver = new ChromeDriver();
		
		
		
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
//		driver.quit();
	}

	@Test
	public void verifyNOPLogin() throws Exception {
		
		Thread.sleep(3000);		
		driver.get("https://admin-demo.nopcommerce.com/login?ReturnUrl=%2Fadmin%2F"); //-----invoke API (REST) JSON
		
		Thread.sleep(5000);	
		driver.findElement(By.id("RememberMe")).click();
//// assertThat(driver.getTitle(), is("Your store. Login"));
//		{
//			List<WebElement> elements = driver.findElements(By.cssSelector(".button-1"));
//			assert (elements.size() > 0);
//		}
//		driver.findElement(By.cssSelector(".button-1")).click();
//// assertThat(driver.getTitle(), is("Dashboard / nopCommerce administration"));
//// assertThat(driver.findElement(By.cssSelector(".content-header > h1")).getText(), is("Dashboard"));
//		driver.findElement(By.linkText("Logout")).click();
//		{
//			List<WebElement> elements = driver.findElements(By.cssSelector(".button-1"));
//			assert (elements.size() > 0);
//		}
	}
}
